like_lion-master/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('signup/', views.signup, name = 'signup'),
    path('logout/', views.logout, name = 'logout'),
    path('profile/', views.profile, name = 'profile'),
]

like_lion-master/main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.main, name="main"),
    path('main/wash/', views.getOrder, name='wash'),
    path('main/wash/search', views.searchCustomer, name='search'),
    path('main/wash/customer/', views.customer, name='customer'),
    path('main/message/', views.message, name='message'),
    path('main/manage/', views.manage, name='manage'),
    path('main/manage/csv', views.saveCSV, name='saveCSV'),
    path('main/process/<int:pk>', views.process, name='process'),
    path('main/end_process/<int:pk>', views.end_process, name='end_process'),

]

like_lion-master/one_day_lesson/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("main.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

like_lion-master/main/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save
from accounts.models import User


class Service(models.Model):
    SERVICE_CATEGORY_CHOICES = (
        ('수선', '수선'),
        ('세탁', '세탁'),
    )
    service = models.CharField(max_length=10, primary_key=True)
    category = models.CharField(max_length=2, choices=SERVICE_CATEGORY_CHOICES)


class Clothe(models.Model):
    CLOTHES_CATEGORY_CHOICES = (
        ('아우터', '아우터'),
        ('상의', '상의'),
        ('하의', '하의'),
        ('원피스', '원피스'),
        ('신발', '신발'),
    )

    clothe = models.CharField(max_length=10, primary_key=True)
    category = models.CharField(
        max_length=10, choices=CLOTHES_CATEGORY_CHOICES)


class Customer(models.Model):
    nickname = models.ForeignKey('accounts.User', on_delete=models.CASCADE, null=True)
    phone_num = models.CharField(max_length=11, null=False, primary_key=True)
    name = models.CharField(max_length=20)
    address = models.TextField()
    get_message = models.SmallIntegerField()
    created_date = models.DateTimeField(default=timezone.now)


class Request(models.Model):
    STATUS = (
        ('처리전', '처리 전'),
        ('처리중', '처리중'),
        ('처리완료', '처리 완료'),
        ('수거완료', '수거 완료'),
    )
    request_num = models.CharField(max_length=20, primary_key=True)
    phone_num = models.ForeignKey('Customer', on_delete=models.CASCADE)
    clothe = models.ForeignKey('Clothe', on_delete=models.CASCADE)
    service = models.ForeignKey('Service', on_delete=models.CASCADE)
    status = models.CharField(max_length=5, choices=STATUS)
    rqst_date = models.DateTimeField(default=timezone.now)
    est_date = models.DateTimeField(null=True)
    fin_date = models.DateTimeField(null=True)
    rtrn_date = models.DateTimeField(null=True)
    requirements = models.TextField(null=True)
    price = models.IntegerField()

    def __str__(self):
        return self.request_num

    def getList(self):
        row = []
        row.append(self.request_num)
        row.append(self.phone_num.phone_num)
        row.append(self.clothe.clothe)
        row.append(self.service.service)
        row.append(self.status)
        row.append(str(self.rqst_date))
        row.append(str(self.est_date))
        row.append(str(self.fin_date))
        row.append(str(self.rtrn_date))
        row.append(self.requiremnets)
        row.append(str(self.price))
        return row

like_lion-master/main/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from accounts.models import User
from .models import  Customer


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        
        fields = [
            'phone_num',
            'name',
            'address',
            'get_message',
        ]
        widgets = {
            'phone_num': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'address': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'get_message': forms.NumberInput(
                attrs={
                    'class': 'form-control',
                }
            ),
        }


class CustomerForm2(forms.Form):
    phone_num = forms.CharField(label='고객번호')
    name = forms.CharField(label='고객명', max_length=30)


class OrderForm(forms.Form):
    est_date = forms.DateField(label='예상완료날짜',
        widget=forms.DateInput(
            attrs={'type': 'date'}
        ))
    requirements = forms.CharField(label='세부요청사항')


class SearchForm(forms.Form):
    word = forms.CharField(label='Search Word')


class SendMessageForm(forms.Form):
    customer_name = forms.CharField(label='이름', required=True)
    customer_number = forms.DecimalField(label='핸드폰 번호', required=True)

   # Options = (
   #     ('1', 'Hello'),
   #     ('2', 'World'),
   # )
   # category = forms.ChoiceField(label='Category', choices=Options)

    input_message = forms.CharField(label='문자 내용', required=True)

like_lion-master/main/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView
from django.conf import settings
from django.db.models import Q
from . import views
from . import models
from django.contrib.auth.forms import UserChangeForm
from django.shortcuts import render, redirect, resolve_url, get_object_or_404
from django.conf import settings
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import get_user_model
from main.forms import CustomerForm, OrderForm, CustomerForm2, SearchForm
from django.contrib import messages
import csv
#from .resources import RequestResource
from django.http import HttpResponse
from django.contrib import messages
from twilio.rest import Client
from .forms import SendMessageForm
from accounts.models import User
from .models import Customer, Request
# in create


class WashView(TemplateView):
    template_name = "main/wash.html"

wash = WashView.as_view()


class CustomerView(CreateView):
    model = Customer
    form_class = CustomerForm
    template_name = "main/customer.html"

    def form_valid(self, form):
        post = form.save(commit = False)
        post.nickname = self.request.user
        post.save() 
        
        return redirect('main:wash')


customer = CustomerView.as_view()



class MessageView(ListView):
    template_name = "main/message.html"
    redirect_authenticated_user = True
    model = Customer

    def get_queryset(self):
        word = self.request.GET.getlist('word')
        queryset = super(MessageView, self).get_queryset()
        if word:
            queryset.filter(
                Q(phone_num__contains=word) |
                Q(name__contains=word)
            )

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MessageView, self).get_context_data(
            object_list=None, **kwargs)
        context['form'] = SearchForm()
        return context

    def get(self, request, *args, **kwargs):
        return super(MessageView, self).get(request, *args, **kwargs)


message = MessageView.as_view()


class ManageView(TemplateView):
    template_name = "main/manage.html"


manageView = ManageView.as_view()


def manage(request):
    request_info = Request.objects.all().select_related("phone_num")
    request_context = {'request_info': request_info}

    return render(request, 'main/manage.html', request_context)


def main(request):
    requests = Request.objects.all()
    return render(request, 'main/main.html', {'requests': requests})

def process(request, pk):
    processed_request = Request.objects.get(request_num=pk)
    processed_request.status = "처리 완료"
    processed_request.save()
    requests = Request.objects.all()
    return render(request, 'main/main.html', {'requests': requests})

def end_process(request, pk):
    end_processed_request = Request.objects.get(request_num=pk)
    end_processed_request.status = "수거 완료"
    end_processed_request.save()
    requests = Request.objects.all()
    return render(request, 'main/main.html', {'requests': requests})


def getOrder(request):
    if request.method == 'POST':
        order_form = OrderForm(request.POST, request.FILES)   
        if order_form.is_valid():
            order_info = Post(**form.cleaned_data)
            order_info.save()
            return HttpResponse("finish")

    elif request.method == 'GET':
        customer = CustomerForm2()
        order = OrderForm()
        return render(request, 'main/wash.html', {'customer': customer, 'order': order})
    else:
        pass


def searchCustomer(request):
    if request.method == "POST":
        form = CustomerForm2(request.POST)
        if form.is_valid():
            customer_list = Customer.objects.filter(
                phone_num=form.cleaned_data['phone_num'], name=form.cleaned_data['name'])
            print(customer_list)
            if len(customer_list) != 0:
                order = OrderForm()
                return render(request, 'main/wash2.html', {'customer': customer_list, 'order': order})
            else:
                context = 'g'
                form = CustomerForm2()
                return render(request, 'main/wash.html', {'customer': customer_list, 'customer': form, 'context': context})
    else:
        return render(request, 'main/wash.html', {'customer': customer_list, 'context': '회원 정보를 찾을 수 없습니다.'})
    # print(customer_list)


def saveCSV(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="noname.csv"'

    writer = csv.writer(response, csv.excel)
    response.write(u'\ufeff'.encode('utf8'))

    join_model = Request.objects.select_related('phone_num')

    writer.writerow([
        str(u"요청번호"),
        str(u"고객번호"),
        str(u"고객이름"),
        str(u"의류"),
        str(u"서비스 종류"),
        str(u"서비스 상태"),
        str(u"요청 날짜"),
        str(u"예상 날짜"),
        str(u"완료 날짜"),
        str(u"찾아간 날짜"),
        str(u"요청사항"),
        str(u"가격"),
        str(u"주소"),
        str(u"가입날짜"),
    ])

    for record in join_model:
        row = []
        row.append(record.request_num)
        row.append(record.phone_num.phone_num)
        row.append(record.phone_num.name)
        row.append(record.clothe.clothe)
        row.append(record.service.service)
        row.append(record.status)
        row.append(str(record.rqst_date))
        row.append(str(record.est_date))
        row.append(str(record.fin_date))
        row.append(str(record.rtrn_date))
        row.append(record.requirements)
        row.append(str(record.price))
        row.append(record.phone_num.address)
        row.append(record.phone_num.created_date)
        print(row)
        writer.writerow(row)

    return response


def message(request):
    form_class = SendMessageForm

    send_message_form = form_class(request.POST or None)
    if request.method == 'POST':

        #send_message_form = SendMessageForm(request.POST)

        if send_message_form.is_valid():
            account_sid = 'AC155820cd778430b90f0b858fb5635d9b'
            auth_token = '888b211e0bfd4cf40237999b30cfad8b'
            client = Client(account_sid, auth_token)

            customer_name = request.POST.get('customer_name')
            customer_number = request.POST.get('customer_number')
            input_number = '+82' + customer_number[1:]

            #category = request.POST.get('category')
            category = send_message_form.cleaned_data.get('category')
            input_message = request.POST.get('input_message')

            message = client.messages.create(
                body=customer_name + "님 " + input_message,
                from_='+12015819428',
                to=input_number
            )
            print(message.sid)
    # GET
    else:
        message = MessageView.as_view()

    context = {
        'form': send_message_form,
    }

    return render(request, 'main/message.html', context)

like_lion-master/main/templates/main/base.html
{% load static %}
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- JQUERY -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" />
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script src="//code.jquery.com/ui/1.8.18/jquery-ui.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  <!-- 카카오 맵 API -->
  <!-- 구글 폰트 API -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- MaerializeCSS CDN -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  {% block title %}
  {% endblock %}
  {% block style %}
  {% endblock %}
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body style="overflow-x: hidden"></body>
<body>
  <div class="App">
    <main>
      {% block main %}
      {% endblock %}
    </main>
    <footer>
        <div class="footer-copyright black-text grey lighten-4">
            <div class="container">
              <div class="copyright center">
                <span class="grey-text text-darken-2">
                  © 2019 Copyright Materials
                  ( Managed and Powered by Team 2 <i class="material-icons tiny blue-text text-lighten-3">build</i> )
                </span>
              </div>
            </div>
          </div>
    {% block footer %}
    {% endblock %}
  </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% block script %}
    {% endblock %}
  </body>
  
  </html>

like_lion-master/main/templates/main/customer.html
{% extends 'main/wash.html' %}
{% load staticfiles %}

{% block script %}

{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/css/wash.css' %}">
{% endblock %}

{% block title %}
<title>신규 고객 등록</title>
{% endblock %}

{% block main %}
<header>
    <nav class="teal lighten-3 z-depth-0">
        <div class="nav-wrapper container">
            <a href="/" class="brand-logo">모두의 세탁소</a>
            
        </div>
    </nav>
</header>
<div class = "customer">
    <form action = "{% url 'main:customer' %}" method="POST">
        {% csrf_token %}
        <h4 class = "center">신규 고객 등록</h4>
        

        <div class = "field">
            <label for = "customer_name">고객명</label>
            <div class = "text">{{form.name}}</div>
        </div>

        <div class = "field">
            <label for = "phone_number">전화번호</label>
            <div class = "text">{{form.phone_num}}</div>
        </div>

        <div class = "field">
            <label for = "address">주소</label>
            <div class = "text">{{form.address}}</div>
        </div>

        <div class = "field">
            <label for = "category">문자 수신여부</label>
            <div class= "check">
                <input type="checkbox" id="check1" name ="check1" />
                <label for = "check1"><span></span> 수신</label>
                <input type="checkbox" id="check2" name ="check2"/>
                <label for = "check2"><span></span> 비수신</label>
            </div>
            <div class = "text">{{form.get_message}}</div>
        </div>
    
        <div class = "fieldcenter">
           <button type="submit"  class = "btn waves-effect waves-light">등록</button>
           <button class = "btn waves-effect waves-light" onclick = 'window.close()'>취소 </button>
        </div>       

    </form>
</div>
{% endblock %}

like_lion-master/main/templates/main/main.html
{% extends 'main/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="stylesheet" href="{% static 'main/css/banner.css' %}">
<link rel="stylesheet" href="{% static 'main/css/card.css' %}">
<link rel="stylesheet" href="{% static 'main/css/parallax.css' %}">
{% endblock %}

{% block title %}
<title>모두의 세탁소</title>
{% endblock %}

{% block main %}
<header>
  <nav class="teal lighten-3 z-depth-0">
    <div class="nav-wrapper container">
      <a href="/" class="brand-logo">모두의 세탁소</a>
      <ul class="right hide-on-med-and-down">
          {% if user.is_authenticated %}
          <li><a href="{% url 'main:wash' %}?next={{ request.get_full_path|urlencode }}" onclick = "window.open(this.href,'','width=600, height=800, scrollbars=yes'); return false">세탁물등록</a></li>
          <li><a href="{% url 'main:manage' %}?next={{ request.get_full_path|urlencode }}">관리부이동</a></li>
          <li><a href="{% url 'main:message' %}?next={{ request.get_full_path|urlencode }}" onclick = "window.open(this.href,'','width=500, height=500'); return false">메시지팝업창</a></li>
          <li><a href="{% url 'accounts:logout' %}?next={{ request.get_full_path|urlencode }}">로그아웃</a></li>
          {% else %}
          
          <li><a href="{% url 'accounts:login' %}">로그인</a></li>
          <li><a href="{% url 'accounts:signup' %}?next={{ request.get_full_path|urlencode }}">회원가입</a></li>
  
          {% endif %}
       </ul>
    </div>
  </nav>
</header>

<div class="main-page">
    <div class="banner-image">
        <div class="container banner-text">
            <h3 id="banner-title">나만의 세탁소, 나만의 공간</h3>
            <p>공간에서 제공하는 클래스를 통해 일상을 충전하세요</p>
        </div>
    </div>
</div>
{% if user.is_authenticated %}
<div class="container-fuild" id="app" style="padding: 0 80px;">
  <br><br><br>
  <div class="position-relative">
      <div class="row d-flex align-items-center" style="height:120px;">
          <h4 class="m-0">어서오세요 {{ request.user.nickname }}님! 오늘의 할일을 확인하세요.</h4>
      </div>
  </div>
</div>

<div class="row" style="border:1px solid rgb(82, 82, 82);"></div> 
<h2>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;할&emsp;&emsp;&emsp;일&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 다한&emsp; 일</h2>
<br>
<table class="col-md-6" id="star_table"> 
  <tr class="text-center">
    <th>OrderName</th>
    <th>고객이름</th>
    <th>옷 분류</th>
    <th>서비스 분류</th>
    <th>예상 완료 날짜</th>
    <th>요청사항</th>
    <th>완료</th>
  </tr>

  {% for request in requests %}
    {% if '처리중' in request.status%}
    <tr class="text-center">
      <th>{{forloop.counter}}</th>
      <th>
        {{ request.request_num }}
      </th>
      <th>{{request.clothe.category}}</th>
      <th>{{request.service.category}}</th>
      <th>{{request.status}}</th>
      <th>{{request.requiremnets}}</th>
      <th> 
        <form action="{% url 'main:process' request.request_num %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="완료">
        </form>
      </th>
    </tr>
    {% endif %}
  {% endfor %}

</table>
<table class="col-md-6" id="star_table"> 
  <tr class="text-center">
    <th>OrderName</th>
    <th>고객이름</th>
    <th>옷 분류</th>
    <th>서비스 분류</th>
    <th>완료 날짜</th>
    <th>요청사항</th>
    <th>수거상태</th>
  </tr>

  {% for request in requests %}
  {% if '처리 완료' in request.status%}
  <tr class="text-center">
    <th>{{forloop.counter}}</th>
    <th>
      {{ request.request_num }}
    </th>
    <th>{{request.clothe.category}}</th>
    <th>{{request.service.category}}</th>
    <th>{{request.status}}</th>
    <th>{{request.requiremnets}}</th>
    <th> 
      <form action="{% url 'main:end_process' request.request_num %}" method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="수거">
      </form>
    </th>
  </tr>
  {% endif %}
{% endfor %}
</table>
{% else %}
<div class="mt-3"><a href="{% url 'accounts:login' %}">로그인 하러 가기</a></div>
<div class="mt-3"><a href="{% url 'accounts:signup' %}">회원가입 하러 가기</a></div>
{% endif%}
{% endblock %}
{% block footer %}
    <hr />ㅇ
    <div class="container grey-text text-darken-3">
      <div class="row">
        <div class="col s10 l6">
          <h5>세탁소</h5>
          <p>세탁소 매장과 사용자들간의 편리한 인터페이스를 제공하고 세탁소 공간, 스페이스(Space)를 제공하는 서비스 '공간'입니다. </p>
        </div>
        <div class="col s12 l5 offset-l1">
        </div>
      </div>
    </div>
  {% endblock %}
{% block script %}
<script>
    $(document).ready(function () {
        $('.modal').modal();
        $('.parallax').parallax();
    });
</script>
{% endblock %}

like_lion-master/main/templates/main/manage.html
{% extends 'main/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/css/message.css' %}">
<header>
    <nav class="teal lighten-3 z-depth-0">
        <div class="nav-wrapper container">
            <a href="/" class="brand-logo">모두의 세탁소</a>
            <ul class="right hide-on-med-and-down">
                <a href="{% url 'main:saveCSV' %}?next={{ request.get_full_path|urlencode }}"  onclick = "">엑셀로 내보내기</a>
            </ul>
        </div>
    </nav>
</header>
{% endblock %}

{% block title %}
  <title>관리대장부</title>
{% endblock %}
{% block main %}
<div class="list_type_h1 web_view mt3">
    <table>
        <thead>
        <tr>
            <td><B>연번</B></td>
            <td><B>고객번호</B></td>
            <td><B>고객이름</B></td>
            <td><B>의류분류</B></td>
            <td><B>요청서비스</B></td>
            <td><B>세부 요청사항</B></td>
            <td><B>맡긴 날짜</B></td>
            <td><B>찾아간 날짜</B></td>
            <td><B>가격</B></td>
        </tr>
        </thead>
        <tbody>
        {% for request in request_info %}
        <tr>
            <td>{{request.request_num}}</td>
            <td>{{request.phone_num.phone_num}}</td>
            <td>{{request.phone_num.name}}</td>
            <td>{{request.clothe.clothe}}</td>
            <td>{{request.service.service}}</td>
            <td>{{request.requirements}}</td>
            <td>{{request.rqst_date}}</td>
            <td>{{request.rtrn_date}}</td>
            <td>{{request.price}}</td>
        </tr>
        {% endfor %}
{% endblock %}

like_lion-master/main/templates/main/message.html
{% extends 'main/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/css/message.css' %}">
<header>
    <nav class="teal lighten-3 z-depth-0">
        <div class="nav-wrapper container">
            <a href="/" class="brand-logo">모두의 세탁소</a>
        </div>
    </nav>
</header>
{% endblock %}

{% block title %}
<title>메시지 전송</title>
{% endblock %}

{% block main %}
<div class="message">
    <!-- <form action="{% url 'main:message' %}" method="post">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="field">
            <label for="customer_name">고객명</label>
            <input type="text" id="customer_name" />
            <button type="submit" class="btn waves-effect waves-light">검색</button>
            <div>{{form.customer_name}}</div>
        </div>

        <div class="field">
            <label for="customer_number">고객번호</label>
            <select id="number_select">
                <option selected>선택하세요</option>
                <option>예1</option>
                <option>예2</option>
            </select>
            <div>{{form.customer_number}}</div>
            <label for="customer_number">고객번호</label>
            <input type="number" id="customer_number" />
        </div>

        <div class="field">
            <label for="select">맡기신 물품</label>
            <select id="select">
                <option selected>선택하세요</option>
                <option>예1</option>
                <option>예2</option>
            </select>
            <div>{{form.subject}}</div>
        </div>

        <div class="field">
            <label for="input_mesage" style="vertical-align: top">문자 내용 입력</label>
            <textarea id="input_message" placeholder="문자를 입력하세요"
                style=" vertical-align: top;width:200px; height:100px; font-size:13px;top: 0px;"></textarea>
            <div>{{form.input_message}}</div>
        </div>

        <div class="fieldcenter">
            <input type="submit" id="send" class="btn waves-effect waves-light">전송</input>
            <button class="btn waves-effect waves-light">취소</button>
        </div>
    </form> -->


    <form action="" method="POST">
        {%  csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="Submit" class="btn waves-effect waves-light">
    </form>

</div>
{% endblock %}


<script src="https://unpkg.com/vue"></script>
<script>
    // var sendMessage = new Vue({
    //     el: '#send_message',
    //     data: {

    //     },
    //     methods: {
    //         send: function (event) {
    //             // const accountSid = 'AC155820cd778430b90f0b858fb5635d9b';
    //             // const authToken = '888b211e0bfd4cf40237999b30cfad8b';
    //             // const client = require('twilio')(accountSid, authToken);

    //             // client.messages
    //             //     .create({
    //             //         body: '문자 전송!',
    //             //         from: '+12015819428',
    //             //         to: '+821037045778'
    //             //     })
    //             //     .then(message => console.log(message.sid));
    //             console.log("send message");
    //         }
    //     }
    // })

    // document.getElementById('send').onclick() = function () {
    //     console.log('send message');
    // }
</script>

like_lion-master/main/templates/main/wash.html
{% extends 'main/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'main/css/wash.css' %}">
<header>
        <nav class="teal lighten-3 z-depth-0">
            <div class="nav-wrapper container">
                <a href="/" class="brand-logo">모두의 세탁소</a>
            </div>
        </nav>
</header>
{% endblock %}

{% block title %}
<title>세탁물 등록</title>
{% endblock %}

{% block main %}
{% if context %}
<script>
    alert("회원 정보를 찾을 수 없습니다.");
</script>
{% endif %}
<div class = "wash">
   <form action = "{% url 'main:search' %}" method="POST">
        <h4 class = "center">세탁물 등록</h4>
        {% csrf_token %}
        {{ customer }}
        <div class="fieldcenter">
        <button type="submit" class = "btn waves-effect waves-light">검색</button>
        </div>
    </form>
<div style="text-align: center;">
    <a href="{% url 'main:customer' %}?next={{ request.get_full_path|urlencode }}" class = "btn waves-effect waves-light" onclick = "window.open(this.href,'','width=550, height=730, scrollbars=yes'); return false">신규고객등록</a>
</div>


</div>
{% endblock %}